### Получить всех сотрудников
GET http://localhost:8080/employees


### Создать сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "   ",
  "lastName": "Ivanov",
  "department": 1,
  "salary": 1000
}

### Создать второго сотрудника
POST http://localhost:8080/employees
Content-Type: application/json

{
  "firstName": "Cemen",
  "lastName": "Cemenov",
  "departmennt": 2,
  "salary": 5000
}


### Получить сумму зарплат
GET http://localhost:8080/employees/salary/sum

### Получить сотрудника с самой большой зарплатой
GET http://localhost:8080/employees/salary/max

### Получить сотрудника с самой маленькой зарплатой
GET http://localhost:8080/employees/salary/min

### Получение всех сотрудников, зарплата которых больше средней зарплаты
GET http://localhost:8080/employees/highSalary


 if (StringUtils.isEmpty("firstName")||StringUtils.isBlank("firstName")){
            System.out.println("Заполните правильно имя сотрудника");
        }
        if (StringUtils.isEmpty("lastName")||StringUtils.isBlank("lastName")){
            System.out.println("Заполните правильно фамилию сотрудника");
        }